#!/usr/bin/env python3
"""Mechanically generated review-status summary, embedded in the docs.

`docs/project_overview.md` and `reviews/README.md` each used to carry a
hand-written paragraph of prose stating how many `review_model` rounds had
run and whether their findings were resolved. That prose had no gate the way
every hash-pinned artifact in this repo does, and it drifted: this file exists
because it drifted twice in one afternoon, caught only by someone asking
whether the docs were still current.

This tool regenerates the block mechanically from the same two sources of
truth `tools/check_review_findings.py` already reads — `reviews/*.findings.yaml`
and `decisions/*.md` — and writes it between a pair of HTML-comment markers in
each managed doc. It deliberately does **not** claim a round count or a
lifetime finding total: a "fixed" finding leaves no durable machine-readable
trace once the code changes (that is what makes its review stale), so the only
claims made here are ones the current repo state can actually support:

  - whether each (ip, kind) review is current or stale, right now
  - what that review's own findings are, when current (all of them dismissed,
    by construction: `check_review_findings.py` would already be failing
    otherwise)
  - the full, durable ledger of every finding ever dismissed by name in
    `decisions/<ip>.md` -- dismissals never disappear, so this list only grows

Usage::

    python tools/report_review_status.py            # print the generated block
    python tools/report_review_status.py --write     # rewrite it into every managed doc
    python tools/report_review_status.py --check     # gate: fail if any managed doc's block is stale
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

try:
    from ._repo_root import find_repo_root
except ImportError:  # not running as part of the `ip_model_automation.tools`
    # package (e.g. `python tools/x.py`, or a test loading this file
    # directly via importlib) -- fall back to a sibling top-level import.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from _repo_root import find_repo_root

REPO_ROOT = find_repo_root()
REVIEWS_DIR = REPO_ROOT / "reviews"
DECISIONS_DIR = REPO_ROOT / "decisions"

# Kept in lockstep with tools/check_review_findings.py's REVIEW_KINDS keys and
# per-kind subject files. Duplicated rather than imported: no tool in this repo
# imports another (each is a standalone, subprocess-composable script), so this
# mirrors the same handful of lines check_overview_sync.py and friends already
# each carry independently.
REVIEW_KINDS: dict[str, dict[str, str]] = {
    "normalization": {
        "source_sha256": "dlds/{ip}_dld.src.md",
        "normalized_sha256": "dlds/{ip}_dld.md",
    },
    "model": {
        "template_sha256": "templates/{ip}.template.yaml",
        "model_sha256": "src/ip_model_automation/{ip}.py",
        "tests_sha256": "tests/test_{ip}.py",
    },
}

DISMISSAL_RE = re.compile(r"\*\*\s*([A-Za-z][\w.-]*)\s+(dismissed|fixed)\s*:?\s*\*\*\s*(.+)", re.IGNORECASE)
FINDING_ID_RE = re.compile(r"^([A-Za-z]+)(\d+)$")

START_MARKER = (
    "<!-- AUTOGEN:review-status:start "
    "(generated by `python tools/report_review_status.py --write`; do not hand-edit) -->"
)
END_MARKER = "<!-- AUTOGEN:review-status:end -->"

# The docs this block is embedded in. Both show the same generated content --
# one narrative kept in two places is how the two drift from each other, not
# just from reality.
MANAGED_DOCS: tuple[Path, ...] = (
    REPO_ROOT / "docs" / "project_overview.md",
    REPO_ROOT / "reviews" / "README.md",
)


def require_yaml():
    try:
        import yaml  # type: ignore
    except ModuleNotFoundError as exc:  # pragma: no cover - environment guard
        raise SystemExit("PyYAML is required. Install project requirements before running this tool.") from exc
    return yaml


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def reviews() -> list[tuple[str, str]]:
    """Every recorded review, as (ip, kind), from `<ip>.<kind>.findings.yaml`."""
    if not REVIEWS_DIR.is_dir():
        return []
    found: list[tuple[str, str]] = []
    for path in sorted(REVIEWS_DIR.glob("*.findings.yaml")):
        stem = path.name[: -len(".findings.yaml")]
        ip, _, kind = stem.rpartition(".")
        if ip and kind in REVIEW_KINDS:
            found.append((ip, kind))
    return found


def load_findings(path: Path) -> dict | None:
    yaml = require_yaml()
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 - unreadable is reported, not crashed on
        return None
    return data if isinstance(data, dict) else None


def dismissals(ip: str) -> dict[str, str]:
    """Finding ids ever dismissed for this ip, from decisions/<ip>.md.

    A durable ledger: dismissal lines are never removed, so this only grows.
    """
    path = DECISIONS_DIR / f"{ip}.md"
    if not path.is_file():
        return {}
    found: dict[str, str] = {}
    for match in DISMISSAL_RE.finditer(path.read_text(encoding="utf-8")):
        if match.group(2).lower() == "dismissed":
            found[match.group(1)] = match.group(3).strip()
    return found


def review_is_stale(data: dict, ip: str, kind: str) -> str | None:
    for key, pattern in REVIEW_KINDS[kind].items():
        path = REPO_ROOT / pattern.format(ip=ip)
        if not path.is_file():
            return f"{path.name} does not exist"
        if data.get(key) != sha256_text(path.read_text(encoding="utf-8")):
            return f"{path.name} changed since this review"
    return None


def sort_key(finding_id: str) -> tuple[str, int, str]:
    match = FINDING_ID_RE.match(finding_id)
    if match:
        return (match.group(1), int(match.group(2)), "")
    return (finding_id, 0, finding_id)


def generate() -> str:
    lines: list[str] = [START_MARKER]
    rows = reviews()
    if not rows:
        lines.append("No `review_model` or `review_normalization` round has been run yet.")
        lines.append(END_MARKER)
        return "\n".join(lines) + "\n"

    lines.append("| IP | Kind | Review status | This round's findings |")
    lines.append("| --- | --- | --- | --- |")
    for ip, kind in rows:
        data = load_findings(REVIEWS_DIR / f"{ip}.{kind}.findings.yaml")
        if data is None:
            lines.append(f"| `{ip}` | {kind} | *(findings file unreadable)* | - |")
            continue
        stale = review_is_stale(data, ip, kind)
        findings = data.get("findings") or []
        ids = sorted((f.get("id") for f in findings if isinstance(f, dict) and f.get("id")), key=sort_key)
        if stale:
            status = f"stale — {stale}; a fresh round is owed"
            found_cell = f"{', '.join(ids)} (superseded)" if ids else "-"
        elif ids:
            status = "current"
            found_cell = ", ".join(ids) + " (dismissed)"
        else:
            status = "current"
            found_cell = "none"
        lines.append(f"| `{ip}` | {kind} | {status} | {found_cell} |")

    if not any(kind == "normalization" for _ip, kind in rows):
        lines.append("")
        lines.append("No `normalization` review has been run against either live IP yet.")

    ledgers = [(ip, dismissals(ip)) for ip in sorted({ip for ip, _kind in rows})]
    ledgers = [(ip, d) for ip, d in ledgers if d]
    if ledgers:
        lines.append("")
        lines.append("Findings dismissed by name to date, from `decisions/<ip>.md`:")
        for ip, dismissed in ledgers:
            ids = sorted(dismissed, key=sort_key)
            lines.append(f"- `{ip}`: {', '.join(ids)}")

    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def replace_block(text: str, generated: str, doc_name: str) -> str:
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{doc_name}: no AUTOGEN:review-status markers found. Add\n"
            f"  {START_MARKER}\n  {END_MARKER}\naround the block to manage."
        )
    end += len(END_MARKER)
    return text[:start] + generated.rstrip("\n") + text[end:]


def check() -> list[str]:
    generated = generate()
    errors: list[str] = []
    for doc in MANAGED_DOCS:
        rel = doc.relative_to(REPO_ROOT)
        if not doc.is_file():
            errors.append(f"{rel}: file does not exist")
            continue
        text = doc.read_text(encoding="utf-8")
        start = text.find(START_MARKER)
        end = text.find(END_MARKER)
        if start == -1 or end == -1:
            errors.append(f"{rel}: no AUTOGEN:review-status markers found")
            continue
        current_block = text[start : end + len(END_MARKER)]
        if current_block.rstrip("\n") != generated.rstrip("\n"):
            errors.append(
                f"{rel}: review-status block is stale. Run "
                "`python tools/report_review_status.py --write` and commit the result."
            )
    return errors


def write() -> None:
    generated = generate()
    for doc in MANAGED_DOCS:
        if not doc.is_file():
            raise SystemExit(f"{doc.relative_to(REPO_ROOT)}: file does not exist")
        text = doc.read_text(encoding="utf-8")
        updated = replace_block(text, generated, str(doc.relative_to(REPO_ROOT)))
        if updated != text:
            doc.write_text(updated, encoding="utf-8")
            print(f"updated {doc.relative_to(REPO_ROOT)}")
        else:
            print(f"{doc.relative_to(REPO_ROOT)} already current")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite the block into every managed doc")
    group.add_argument("--check", action="store_true", help="gate: fail if any managed doc's block is stale")
    args = parser.parse_args(argv)

    if args.write:
        write()
        return 0

    if args.check:
        errors = check()
        if errors:
            for error in errors:
                print(f"review status: {error}")
            return 1
        print("review status: OK (every managed doc matches the current review state)")
        return 0

    print(generate())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
